# Use OpenJDK 17 from Eclipse Adoptium
FROM eclipse-temurin:17.0.13_11-jre

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container at /app
COPY /build/libs/redshift-data-api-async-0.0.1-SNAPSHOT.jar /app

# Expose port 8080 for the application
EXPOSE 8080

# Run the JAR file
CMD ["java", "-jar", "redshift-data-api-async-0.0.1-SNAPSHOT.jar"]
